### ISSUE TITLE
'remove' command

### ISSUE THREAD

**Issue by max-mapper** [mafintosh/taco-nginx#1]
e.g. `taco-nginx remove test` would remove the test.conf that this previously generated, and reload nginx

**Comment by max-mapper** [comment]
on further thought I think this should happen when the taco-nginx process exits so that conf files arent hanging around aftewards

**Comment by mafintosh** [comment]
ah yea that sounds like a good idea. i'll add that

**Comment by max-mapper** [comment]
woot
